# Generated by Django 5.0.7 on 2024-08-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
    ]
