# Generated by Django 5.0.7 on 2024-08-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_remove_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
