# Generated by Django 5.0.7 on 2024-08-02 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_tag_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
